### ISSUE TITLE
e3dbb9841a022a02b513047a2c19fe2b014d621c my wallet 
e3dbb9841a022a02b513047a2c19fe2b014d621cB4OPDQ34ZN6IF3V4

### ISSUE THREAD

**Issue by Nordtom** [Nordtom/Flashback-#6]
https://github.com/octocat/Spoon-Knife/commit/e3dbb9841a022a02b513047a2c19fe2b014d621c

**Comment by Generalresolution03** [comment]
Hello @Nordtom
Can you provide more details regarding this issue?
